name: Cypress Tests on push to Main

on:
  push:
    branches: ["main"]

env: 
  BACKEND_TESTS: "cypress/e2e/backend/tests/*.cy.ts"
  FRONTEND_TESTS: "cypress/e2e/frontend/tests/*.cy.ts"
  PROJECT_DIR: /__w/ntt-data-brasil-test/ntt-data-brasil-test

concurrency:
  group: cypress-tests-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node dependencies
        run: npm install
        working-directory: ${{ env.PROJECT_DIR }}

      - name: details dependencies
        run: npm fund
        working-directory: ${{ env.PROJECT_DIR }}

  backend_tests:
    needs: build
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node dependencies
        run: npm install
        working-directory: ${{ env.PROJECT_DIR }}

      - name: run backend tests
        run: |
          for i in 1 2 3; do
            npx cypress run --spec "${{ env.BACKEND_TESTS }}" --headless && break
            echo "Retry #$i failed, retrying in 5s..."
            sleep 5
          done
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: login-videos
          path: ${{ env.PROJECT_DIR }}/cypress/videos

  frontend_tests:
    needs: backend_tests
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node dependencies
        run: npm install
        working-directory: ${{ env.PROJECT_DIR }}

      - name: run frontend tests
        run: |
          for i in 1 2 3; do
            npx cypress run --spec "${{ env.FRONTEND_TESTS }}" --headless && break
            echo "Retry #$i failed, retrying in 5s..."
            sleep 5
          done
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: participantes-videos
          path: ${{ env.PROJECT_DIR }}/cypress/videos
