name: Cypress Tests on push to Main

on:
  push:
    branches: ["main"]

env: 
  BACKEND_TESTS: "cypress/e2e/backend/tests/*.cy.ts"
  FRONTEND_TESTS: "cypress/e2e/frontend/tests/*.cy.ts"
  
concurrency:
  group: cypress-tests-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node dependencies
        run: npm install
        working-directory: /__w/ntt-data-brasil-test/ntt-data-brasil-test

      - name: details dependencies
        run: npm fund
        working-directory: /__w/ntt-data-brasil-test/ntt-data-brasil-test

  backend_tests:
    needs: build
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node dependencies
        run: npm install
        working-directory: /__w/ntt-data-brasil-test/ntt-data-brasil-test

      - name: tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 7
          max_attempts: 3
          retry_on: error
          command: npx cypress run --spec "${{ env.BACKEND_TESTS }}" --headless
        working-directory: /__w/ntt-data-brasil-test/ntt-data-brasil-test

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: login-videos
          path: /__w/ntt-data-brasil-test/ntt-data-brasil-test/cypress/videos

  frontend_tests:
    needs: backend_tests
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node dependencies
        run: npm install
        working-directory: /__w/ntt-data-brasil-test/ntt-data-brasil-test

      - name: tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 7
          max_attempts: 3
          retry_on: error
          command: npx cypress run --spec "${{ env.FRONTEND_TESTS }}" --headless
        working-directory: /__w/ntt-data-brasil-test/ntt-data-brasil-test

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: participantes-videos
          path: /__w/ntt-data-brasil-test/ntt-data-brasil-test/cypress/videos
