name: Cypress Tests on Pull Requests to Develop

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install node dependencies
        run: npm install
      - name: details dependencies
        run: npm fund

