name: Cypress Tests on push to Main

on:
  push:
    branches: ["main"]

env: 
  BACKEND_TESTS: "cypress/e2e/backend/tests/*.cy.ts"
  FRONTEND_TESTS: "cypress/e2e/frontend/tests/*.cy.ts"
  
concurrency:
  group: cypress-tests-${{ github.ref }}
  cancel-in-progress: false

jobs:
  backend_tests:
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node dependencies
        run: npm install

      - name: Run backend Cypress tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 7
          max_attempts: 3
          retry_on: error
          command: npx cypress run --spec "${{ env.BACKEND_TESTS }}" --headless

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: login-videos
          path: cypress/videos

  frontend_tests:
    needs: backend_tests
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node dependencies
        run: npm install

      - name: Run frontend Cypress tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 7
          max_attempts: 3
          retry_on: error
          command: npx cypress run --spec "${{ env.FRONTEND_TESTS }}" --headless

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: participantes-videos
          path: cypress/videos
